Grace-Shopper-Hoppers/Grace-Shopper-1

- script/seed.js
- server/api/index.js
- server/api/products.js
- server/db/models/index.js
> working on api

- client/components/addProduct.js
- client/components/addProductForm.js
- client/components/index.js
- client/routes.js
- client/store/index.js
- client/store/product.js
- server/api/products.js
- server/db/models/product.js
Has new feature for admin to add product to database and new components for the admin add new feature form
---
> Add new prod14

- client/components/allProducts.js
- client/components/index.js
- client/store/product.js
- server/api/categories.js
- server/api/index.js
- server/api/products.js
- server/api/users.js
> 12frontend

- client/store/product.js
- server/api/products.js
Completed put route to add new products and added thunks and action creators to the store 
---
> 15 completed put route and added thunks and action creator

- client/components/editProduct.js
- client/components/editProductForm.js
- client/components/index.js
- client/routes.js
- client/store/product.js
- server/api/index.js
Finished edit component and edit component form 
---
> 28 finished edit component

- client/components/main.js
- client/store/product.js
- public/style.css
- script/seed.js
- server/db/models/user.js
> Feature12-main-product-view

- client/components/categories.js
- client/components/editProduct.js
- client/components/main.js
- client/components/singleProduct.js
- client/routes.js
- client/store/product.js
- server/api/index.js
- server/api/products.js
- server/auth/index.js
Removed console.logs before code review
---
> console logs gone

- client/components/main.js
- client/routes.js
- client/store/category.js
> fix-git-merge

- client/components/cart.js
- client/store/product.js
- script/seed.js
- server/api/products.js
- server/db/models/order.js
- server/db/models/user.js
> feature-cart-skeleton-41

- client/components/cart.js
- client/components/cartItems.js
- client/components/categories.js
- client/components/index.js
- client/components/main.js
- client/components/navbar.js
- client/components/singleProduct.js
- client/routes.js
- client/store/order.js
- script/seed.js
> Feat: create session storage for guest cart_#43

- client/components/cart.js
- client/components/cartLogIn.js
- client/components/navbar.js
- client/store/order.js
- server/api/index.js
- server/api/order.js
- server/db/models/index.js
> Feature logged in cart

- client/components/cartItems.js
- client/components/checkout.js
- client/components/index.js
- client/components/main.js
- client/components/singleProduct.js
- client/routes.js
> fix add product to sessionStorage function in main js

- client/components/cartLogIn.js
- client/components/categories.js
- client/components/index.js
- client/components/main.js
- client/components/selectedCategory.js
- client/components/selectedProduct.js
- client/components/singleProduct.js
- client/routes.js
- client/store/index.js
- client/store/selectedCategory.js
- client/store/selectedProduct.js
- script/seed.js
- server/api/reviews.js
- server/db/models/index.js
- server/db/models/order.js
- server/db/models/review.js
> Fix git merge issue

- client/components/cartItems.js
- client/components/main.js
- client/components/search.js
---
Feature: Added search bar in main.js and merged with new master
> 51 search bar feature

- server/api/order.js
> feature-orderApi-adds stauts of created to order

- client/components/search.js
> feat: search results redirect

- client/components/navbar.js
- client/components/selectedProduct.js
- client/routes.js
> feature-products-view

- client/components/buttons.js
- client/components/cart.js
- client/components/cartItems.js
- client/components/main.js
- client/components/search.js
- client/components/singleProduct.js
- public/index.html
---
Buttons feature complete. Merged with updated Travis.
> 49 increment decrement buttons

- client/components/addReview.js
- client/components/addReviewForm.js
- client/components/cart.js
- client/components/cartItems.js
- client/components/checkout.js
- client/components/checkoutForm.js
- client/components/index.js
- client/components/navbar.js
- client/components/selectedCategory.js
- client/components/selectedProduct.js
- client/components/takeMoney.js
- client/routes.js
- client/store/checkout.js
- client/store/index.js
- client/store/order.js
- client/store/reviews.js
- client/store/selectedCategory.js
- package-lock.json
- package.json
- script/seed.js
- server/api/categories.js
- server/api/index.js
- server/api/order.js
- server/api/products.js
- server/api/reviews.js
- server/db/models/index.js
- server/db/models/product.js
- server/db/models/review.js
> Fixed reviews

- client/components/buttons.js
- client/components/cart.js
- client/components/cartItems.js
- client/components/index.js
- client/components/main.js
- client/components/navbar.js
- client/components/orderHistory.js
- client/routes.js
- client/store/order.js
- server/api/order.js
> Feature back end edit cart

- client/components/selectedProduct.js
- client/routes.js
- client/store/selectedProduct.js
---
fix: selected product view for logged in user
> fixed selected-product view for logged in users

- client/store/order.js
- script/seed.js
- server/db/models/product.js
> fix: seed file create orders

- client/components/buttons.js
- client/components/cart.js
- client/components/cartItems.js
- client/components/main.js
- client/components/orderHistory.js
- client/store/order.js
- script/seed.js
- server/api/order.js
- server/api/products.js
- server/db/models/index.js
---
Cart is fully functional for logged in users. All bugs fixed, including: cart total, database total, adding and removing items from the main page and editing/removing items from cart component.
> 93 feat working cart

- client/components/addReview.js
- client/components/addReviewForm.js
- client/components/cart.js
- client/components/cartItems.js
- client/components/checkout.js
- client/components/index.js
- client/components/navbar.js
- client/components/selectedProduct.js
- client/components/singleProduct.js
- client/components/takeMoney.js
- client/components/toastNotification.js
- client/store/reviews.js
- package-lock.json
- package.json
- script/seed.js
- server/api/checkout.js
- server/api/email.js
- server/api/index.js
- server/api/products.js
- server/api/reviews.js
> Fixed add review

- client/components/adminHome.js
- client/components/cart.js
- client/components/thankYou.js
- client/routes.js
> cart fixed

- README.md
- client/store/product.spec.js
---
New readMe and a new test added
> 96-test complete and readMe

- README.md
- client/components/cart.js
- client/components/main.js
- client/components/navbar.js
- server/api/order.js
> cart fix for guest user

- client/components/cart.js
- client/components/checkout.js
- client/components/checkoutForm.js
- client/components/index.js
- client/components/main.js
- client/components/promoCode.js
- client/components/thankYou.js
- client/routes.js
- client/store/order.js
- server/api/order.js
- server/db/models/order.js
---
91 - Promo code feature added. Also, thank you route is complete.
> feat: promo code complete and feat: thank you route complete

- client/components/auth-form.js
- server/auth/index.js
---
fix: guest cart clear on log in
> fix: guest cart clears after log in

- client/routes.js
---
fix: routes work for logged in users
> routes fixed

- client/components/index.js
- client/components/selectedCategory.js
- client/components/singleProduct.js
- package-lock.json
- package.json
> Bundle fix
